# Generated by Django 5.0.6 on 2025-05-17 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiving_location',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receiving_location', to='order.order'),
        ),
    ]
