# Generated by Django 5.0.6 on 2025-05-21 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_receiving_location_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20)),
                ('driver_name', models.CharField(max_length=50)),
                ('size', models.IntegerField()),
                ('space', models.IntegerField()),
                ('number_of_orders', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='truck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='order.truck'),
        ),
    ]
