# Generated by Django 5.0.6 on 2025-05-21 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_truck_order_truck'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
