# Generated by Django 5.0.6 on 2025-05-21 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_delete_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cargo', to='order.order'),
        ),
        migrations.AlterField(
            model_name='destination_location',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_location', to='order.order'),
        ),
    ]
